/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.appbanco.Formularios;

import com.unab.edu.appbanco.DAO.ClsCuentasUsuario;
import com.unab.edu.appbanco.Entidades.CuentasUsuario;
import com.unab.edu.appbanco.Entidades.TipoUsuario;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael
 */
public class frmRetiro extends javax.swing.JFrame {

    /**
     * Creates new form prueba2
     */
    public frmRetiro() {
        initComponents();
        MostrarTransacciones();
        setResizable(false);
    }

    public int id;

    public void actualizar() {
        MostrarTransacciones();
    }
  
SimpleDateFormat formato = new SimpleDateFormat("y MMM d");
    void MostrarTransacciones() {
  double Saldo = 0;
        String TITULOS[] = {"SALDO", "TRANSACCION", "FECHA"};
        DefaultTableModel ModeloTabla = new DefaultTableModel(null, TITULOS);
        ClsCuentasUsuario cuenta = new ClsCuentasUsuario();
        CuentasUsuario CU = new CuentasUsuario();
        CU.setIdUsuario(id);
        ArrayList<CuentasUsuario> lista = cuenta.lista(CU);
        String filas[] = new String[3];
        
        for (var i : lista) {
            filas[0] = String.valueOf(i.getSaldo());
            if (i.getTransaccion() == 1) {
                filas[1] = String.valueOf("Abono");
                Saldo = Saldo + i.getSaldo();
            } else {
                filas[1] = String.valueOf("Retiro");
                Saldo = Saldo - i.getSaldo();
            }
            filas[2] =formato.format(i.getFecha());
            ModeloTabla.addRow(filas);
            lblSaldo.setText(String.valueOf(Saldo));
        }
        tbTransaccion.setModel(ModeloTabla);

    }
    
    void limpiar() {
        txtRetiro.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRetirar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTransaccion = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtRetiro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRetirar.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 12)); // NOI18N
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 203, 103, -1));

        tbTransaccion.setBackground(new java.awt.Color(255, 204, 153));
        tbTransaccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbTransaccion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 276, 430, 220));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/retirar.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, 88));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel1.setText("Cantidad que desea retirar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 171, 24));

        txtRetiro.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        txtRetiro.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtRetiroInputMethodTextChanged(evt);
            }
        });
        txtRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRetiroActionPerformed(evt);
            }
        });
        txtRetiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRetiroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRetiroKeyReleased(evt);
            }
        });
        jPanel1.add(txtRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 165, -1));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 2, 36)); // NOI18N
        jLabel2.setText("Retiros");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 140, 50));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel3.setText("HISTORIAL DE TRANSACCIONES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 234, -1, 24));

        lblSaldo.setFont(new java.awt.Font("Noto Serif Cond", 0, 14)); // NOI18N
        lblSaldo.setText("0");
        jPanel1.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 103, 29));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel4.setText("Saldo Disponible");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 100, 24));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casa.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 60));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  int cantidad=0;
    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        int reciduo;
        
        
        reciduo = cantidad%5;
        if(reciduo==0){
        if ((cantidad)<=Double.valueOf(lblSaldo.getText())&& cantidad>0) {
            try {
                CuentasUsuario CuentasUsu = new CuentasUsuario();
                ClsCuentasUsuario ClsCU = new ClsCuentasUsuario();
                CuentasUsu.setIdUsuario(id);
                CuentasUsu.setSaldo(Double.valueOf(txtRetiro.getText()));
                ClsCU.InsertarRetiro(CuentasUsu);
                txtRetiro.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
            }
        }else{
        JOptionPane.showMessageDialog(null, "No se puede realizar la transaccion");
        txtRetiro.setText("");
        }
        MostrarTransacciones();
    }//GEN-LAST:event_btnRetirarActionPerformed
        else {
        JOptionPane.showMessageDialog(null, "La cantidad a retirar debe ser multipo de 5");
        txtRetiro.setText("");
        }
    }
    private void txtRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRetiroActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtRetiroActionPerformed

    private void txtRetiroInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtRetiroInputMethodTextChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtRetiroInputMethodTextChanged

    private void txtRetiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRetiroKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtRetiroKeyPressed

    private void txtRetiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRetiroKeyReleased
        // TODO add your handling code here:
             try {
           cantidad = Integer.valueOf(txtRetiro.getText());
        } catch (Exception e) {
            txtRetiro.setText("");
        }
    }//GEN-LAST:event_txtRetiroKeyReleased

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       frmLogin loguin = new frmLogin();
       loguin.show();
       dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRetiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTable tbTransaccion;
    private javax.swing.JTextField txtRetiro;
    // End of variables declaration//GEN-END:variables
}
